// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWrh5URzOluKhlr1Zpx0JaObp5SOT_3ew',
    appId: '1:729224509362:android:bef69b8ab9ee105eb896ab',
    messagingSenderId: '729224509362',
    projectId: 'parallelchat-e4a59',
    storageBucket: 'parallelchat-e4a59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxfZzI8zVdbs8bQUtMre-iSxzsF8bQzwk',
    appId: '1:729224509362:ios:52832a0749b504a9b896ab',
    messagingSenderId: '729224509362',
    projectId: 'parallelchat-e4a59',
    storageBucket: 'parallelchat-e4a59.appspot.com',
    iosClientId: '729224509362-cibror2mihco0ukt8hiavimjdngabuun.apps.googleusercontent.com',
    iosBundleId: 'ng.ttomatoes.parallelchat',
  );
}
